name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if your main branch is called that

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or whatever Node version you want

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy _redirects
        run: cp _redirects dist/_redirects

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist